// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5kmsEoDVAquZF5yKmRHVpdBO8yHIwGAw',
    appId: '1:890871142497:web:fab12dd5141736d4377220',
    messagingSenderId: '890871142497',
    projectId: 'dictado-a9b35',
    authDomain: 'dictado-a9b35.firebaseapp.com',
    storageBucket: 'dictado-a9b35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgBtJ4rMCf19ucD0LsjZ3u9r2fjRIzsyA',
    appId: '1:890871142497:android:840146708261f285377220',
    messagingSenderId: '890871142497',
    projectId: 'dictado-a9b35',
    storageBucket: 'dictado-a9b35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZRsoFE63y9NBsn4KOYmpwSBkhIfh8Z2w',
    appId: '1:890871142497:ios:e4d45869ba577461377220',
    messagingSenderId: '890871142497',
    projectId: 'dictado-a9b35',
    storageBucket: 'dictado-a9b35.appspot.com',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZRsoFE63y9NBsn4KOYmpwSBkhIfh8Z2w',
    appId: '1:890871142497:ios:5ed54e9b058a4b5a377220',
    messagingSenderId: '890871142497',
    projectId: 'dictado-a9b35',
    storageBucket: 'dictado-a9b35.appspot.com',
    iosBundleId: 'com.example.proyectofinal.RunnerTests',
  );
}
